#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI

bspc config border_width        2
bspc config window_gap          8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config top_padding 40

bspc rule -a Firefox desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a Zathura desktop='^3'

bspc config focus_follows_pointer false

bspc config normal_border_color "#272e33"
bspc config focused_border_color "#a7c080"
#bspc config focused_border_color "#c0caf5"
bspc config active_border_color "#1a1b26"

picom -b --config ~/.config/picom/config.ini &
bash ~/.config/polybar/launch.sh &
nitrogen --restore &
xsetroot -cursor_name left_ptr
setxkbmap -option grp:alt_shift_toggle us,ru
bspc rule -a zenity state=floating
